package au.org.ala.sds.validation;

import au.org.ala.sds.model.SensitivityZone;
import au.org.ala.sds.util.SensitivityZoneHelper;
import au.org.ala.sds.validation.ValidationReport;
import org.drools.runtime.rule.RuleContext;

global ValidationReport validationReport;
global Boolean complete;
global String delegateRules;
global Boolean loadable;

import function au.org.ala.sds.validation.ValidationHelper.*;

rule "In Australia"
    when
        $zone : SensitivityZone()
        eval(SensitivityZoneHelper.isInAustralia($zone))
    then
        System.out.println(drools.getRule().getName());
        //warning(drools, );
end

rule "In External Territory"
     when
        $zone : SensitivityZone()
         eval(SensitivityZoneHelper.isExternalTerritory($zone))
    then
        System.out.println(drools.getRule().getName());
        //error();
end

rule "In Torres Strait Protected Zone"
    when
        $zone : SensitivityZone()
        eval($zone == SensitivityZone.TSPZ)
    then        
        System.out.println(drools.getRule().getName());
end

rule "Not Australian"
    when
        not SensitivityZone()
    then
        System.out.println(drools.getRule().getName());
end