package au.org.ala.sds.validation;

import au.org.ala.sds.model.SensitiveTaxon;
import au.org.ala.sds.model.SensitivityZone;
import au.org.ala.sds.util.PlantPestUtils;
import au.org.ala.sds.validation.RuleState;
import au.org.ala.sds.validation.ValidationReport;
import java.util.Date;
import java.util.Set;
import org.apache.log4j.Logger;
import org.drools.runtime.rule.RuleContext;

global ValidationReport validationReport;
global RuleState state;
global Logger logger;

import function au.org.ala.sds.validation.ValidationHelper.*;

rule "Inside PQA during eradication period"
    when
        $st : SensitiveTaxon()
        $zones : Set()
        $date : Date()
        eval(PlantPestUtils.isInZoneDuringPeriod($st, $zones, $date))
    then
        state.setLoadable(true);
        state.setAnnotation("Record from a current eradication program");
        logger.warn("PBC3 Rule '" + kcontext.getRule().getName() + "'");
        //warning(kcontext, );
end

rule "Inside PQA earlier than eradication period"
    when
        $st : SensitiveTaxon()
        $zones : Set()
        $date : Date()
        eval(PlantPestUtils.isInZoneBeforePeriod($st, $zones, $date))
    then
        state.setLoadable(true);
        state.setAnnotation("Historic record from a current eradication program");
        logger.warn("PBC3 Rule '" + kcontext.getRule().getName() + "'");
end

rule "Outside PQA"
    when
        $st : SensitiveTaxon()
        $zones : Set()
        eval(PlantPestUtils.isOutsideZone($st, $zones))
    then        
        state.setDelegateRules("PBC1");
        state.setComplete(false);
        logger.warn("PBC3 Rule '" + kcontext.getRule().getName() + "'");
end