package au.org.ala.sds.validation;

import au.org.ala.sds.model.SensitiveSpecies;
import au.org.ala.sds.model.SensitivityZone;
import au.org.ala.sds.util.PlantPestUtils;
import au.org.ala.sds.validation.RuleState;
import au.org.ala.sds.validation.ValidationReport;
import java.util.Date;
import java.util.Set;
import org.apache.log4j.Logger;
import org.drools.runtime.rule.RuleContext;

global ValidationReport validationReport;
global RuleState state;
global Logger logger;

import function au.org.ala.sds.validation.ValidationHelper.*;

rule "Inside infested zone during infestation period"
    when
        $st : SensitiveTaxon()
        $zones : Set()
        $date : Date()
        eval(PlantPestUtils.isInZoneDuringPeriod($st, $zones, $date))
    then
        state.setLoadable(true);
        state.setAnnotation("Historic record from {0} infested area established in {1}");
        logger.warn("PBC4 Rule '" + kcontext.getRule().getName() + "'");
        //warning(kcontext, );
end

rule "Inside infested zone prior to infestation period"
    when
        $st : SensitiveTaxon()
        $zones : Set()
        $date : Date()
        eval(PlantPestUtils.isInZoneBeforePeriod($st, $zones, $date))
    then
        state.setLoadable(true);
        state.setAnnotation("Historic record from {0} infested area that predates the first official record {1}");
        logger.warn("PBC4 Rule '" + kcontext.getRule().getName() + "'");
end

rule "Outside infested area"
    when
        $st : SensitiveTaxon()
        $zones : Set()
        eval(PlantPestUtils.isOutsideZone($st, $zones))
    then        
        state.setDelegateRules("PBC6");
        state.setComplete(false);
        logger.warn("PBC4 Rule '" + kcontext.getRule().getName() + "'");
end